# Generated by Django 4.2.2 on 2023-06-06 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
